export const treeTypes = ["Leñoso Alto", "Leñoso Bajo", "Suculento", "Herbáceo"]

export const treeNames = {
	"Leñoso Alto": [
		"Acacia caven",
		"Aristotelia chilensis",
		"Cryptocarya alba",
		"Drimys winteri",
		"Jubaea chilensis",
		"Kageneckia angustifolia",
		"Kageneckia oblonga",
		"Lithraea caustica",
		"Luma chequen",
		"Malus domestica (Borkh.)",
		"Maytenus boaria",
		"Porlieria chilensis",
		"Prosopis chilensis",
		"Pyrus cummunis",
		"Quillaja saponaria",
		"Salix humboldtiana",
		"Schinus latifolius",
		"Schinus polygamus",
	],
	"Leñoso Bajo": [
		"Adesmia confusa",
		"Atriplex atacamensis",
		"Tetragonia angustifolia",
		"Adesmia glutinosa",
		"Adesmia microphylla",
		"Adesmia pedicellata",
		"Adesmia subterranea",
		"Adesmia zoellneri",
		"Aldama revoluta",
		"Atriplex deserticola",
		"Anisomeria littoralis",
		"Azara celastrina",
		"Azorella madreporica",
		"Azorella prolifera",
		"Azorella ruizii",
		"Baccharis linearis",
		"Baccharis neaei",
		"Baccharis paniculata",
		"Baccharis poeppigiana",
		"Baccharis sagittalis",
		"Baccharis salicifolia",
		"Bahia ambrosioides",
		"Berberis empetrifolia",
		"Bridgesia incisifolia",
		"Calceolaria corymbosa",
		"Calceolaria dentata",
		"Calceolaria hypericina",
		"Calceolaria polifolia",
		"Centaurea chilensis",
		"Cestrum parqui",
		"Chiropetalum berterianum",
		"Chorizanthe virgata",
		"Chuquiraga oppositifolia",
		"Chusquea cumingii",
		"Cissus striata",
		"Colletia hystrix",
		"Colliguaja integerrima",
		"Colliguaja odorifera",
		"Colliguaja salicifolia",
		"Diplolepis geminiflora",
		"Diplolepis nummulariifolia",
		"Discaria trinervis",
		"Ephedra chilensis",
		"Ephedra gracilis",
		"Erigeron leptopetalus",
		"Escallonia illinita",
		"Escallonia myrtoidea",
		"Escallonia pulverulenta",
		"Escallonia revoluta",
		"Eupatorium glechonophyllum",
		"Eupatorium salvium",
		"Fabiana imbricata",
		"Flourensia thurifera",
		"Galium suffruticosum",
		"Gardoquia gilliesii",
		"Gochnatia foliolosa",
		"Guindilia trinervis",
		"Gutierrezia resinosa",
		"Gymnophyton isatidicarpum",
		"Haplopappus angustifolius",
		"Haplopappus arbutoides",
		"Haplopappus bezanillanus",
		"Haplopappus cerberoanus",
		"Haplopappus pulchellus",
		"Haplopappus racemiger",
		"Haplopappus retinervius",
		"Haplopappus scrobiculatus",
		"Haplopappus velutinus",
		"Heliotropium stenophyllum",
		"Junellia uniflora",
		"Krameria cistoidea",
		"Lepechinia salviae",
		"Ligaria cuneifolia",
		"Llagunoa glandulosa",
		"Lobelia excelsa",
		"Lobelia polyphylla",
		"Lycium chilense",
		"Malesherbia fasciculata",
		"Malesherbia linearifolia",
		"Margyricarpus pinnatus",
		"Muehlenbeckia hastulata",
		"Mulguraea scoparia",
		"Mutisia acerosa",
		"Mutisia ilicifolia",
		"Mutisia latifolia",
		"Mutisia rosea",
		"Mutisia spectabilis",
		"Mutisia subulata",
		"Nolana rostrata",
		"Ophryosporus paradoxus",
		"Otholobium glandulosum",
		"Pleocarphus revolutus",
		"Pleurophora pungens",
		"Podanthus mitiqui",
		"Proustia cuneifolia",
		"Retanilla trinervia",
		"Ribes trilobum",
		"Senecio crithmoides",
		"Senecio eruciformis",
		"Senecio pissisi",
		"Senecio polygaloides",
		"Solanum crispum",
		"Sphaeralcea obtusiloba",
		"Spinoliva ilicifolia",
		"Tessaria absinthioides",
		"Tetraglochin alatum",
		"Teucrium bicolor",
		"Trevoa quinquenervia",
		"Tristerix aphyllus",
		"Tristerix corymbosus",
		"Tristerix verticillatus",
		"Valeriana stricta",
		"Viviania crenata",
		"Viviania marifolia",
	],
	"Suculento": [
		"Cumulopuntia sphaerica",
		"Echinopsis chiloensis",
		"Tillandsia sp.",
		"Eriosyce aurata",
		"Eriosyce curvispina",
		"Eriosyce senilis",
		"Eriosyce subgibbosa",
		"Eulychnia acida",
		"Maihueniopsis glomerata",
		"Puya alpestris",
	],
	"Herbáceo": [
		"Adesmia tenella",
		"Amsinckia calycina",
		"Argylia radiata",
		"Anthemis cotula",
		"Astragalus berterianus",
		"Avena barbata",
		"Bowlesia uncinata",
		"Bromus berteroanus",
		"Calandrinia compressa",
		"Camissonia dentata",
		"Chaetanthera depauperata",
		"Chaetanthera euphrasioides",
		"Chaetanthera glabrata",
		"Chaetanthera linearis",
		"Chaetanthera microphylla",
		"Chaetanthera moenchioides",
		"Chenopodium album",
		"Chorizanthe commissuralis",
		"Cistanthe celosioides",
		"Cistanthe longiscapa",
		"Collomia biflora",
		"Conium maculatum",
		"Conyza bonariensis",
		"Cristaria dissecta",
		"Cristaria sp.",
		"Cryptantha globulifera",
		"Cryptantha glomerata",
		"Cryptantha sp.",
		"Cryptantha linearis",
		"Cuscuta chilensis",
		"Daucus pusillus",
		"Descurainia nuttallii",
		"Erodium botrys",
		"Erodium cicutarium",
		"Erodium malacoides",
		"Fumaria parviflora",
		"Galium aparine",
		"Gastridium phleoides",
		"Gastridium ventricosum",
		"Gayophytum micranthum",
		"Helenium aromaticum",
		"Hirschfeldia incana",
		"Holcus lanatus",
		"Homalocarpus dichotomus",
		"Hordeum murinum",
		"Isolepis cernua",
		"Lactuca serriola",
		"Lastarriaea chilensis",
		"Leucheria cerberoana",
		"Leucheria tenuis",
		"Loasa floribunda",
		"Loasa heterophylla",
		"Loasa tricolor",
		"Loasa triloba",
		"Logfia gallica",
		"Madia chilensis",
		"Malesherbia humilis",
		"Microseris pygmaea",
		"Montiopsis capitata",
		"Montiopsis cumingii",
		"Montiopsis glomerata",
		"Montiopsis trifida",
		"Moscharia pinnatifida",
		"Nicotiana corymbosa",
		"Oriastrum chilense",
		"Oriastrum pulvinatum",
		"Oxalis laxa",
		"Oxalis micrantha",
		"Oxalis rosea",
		"Pectocarya linearis",
		"Phacelia cumingii",
		"Phalaris amethystina",
		"Plagiobothrys myosotoides",
		"Plantago hispidula",
		"Plantago rancaguae",
		"Pleurophora polyandra",
		"Pleurophora pusilla",
		"Ranunculus muricatus",
		"Rostraria cristata",
		"Salsola kali",
		"Schizanthus alpestris",
		"Schizanthus hookeri",
		"Schizanthus parvulus",
		"Scyphanthus elegans",
		"Senecio vulgaris",
		"Sicyos baderoa",
		"Sisymbrium orientale",
		"Solanum nigrum",
		"Stellaria media",
		"Trifolium campestre",
		"Tallo rojo",
		"Veronica anagallis-aquatica",
		"Vicia vicina",
		"Viola polypoda",
		"Viola subandina",
		"Vulpia bromoides",
		"Vulpia myuros",
		"Acaena pinnatifida",
		"Acaena splendens",
		"Adesmia mucronata",
		"Adiantum chilense",
		"Adiantum excisum",
		"Adiantum sulphureum",
		"Alonsoa meridionalis",
		"Alstroemeria angustifolia",
		"Alstroemeria pulchra",
		"Anemone decapetala",
		"Anisomeria coriacea",
		"Arenaria serpens",
		"Arundo donax",
		"Asteriscium chilense",
		"Baccharis glutinosa",
		"Blechnum hastatum",
		"Calandrinia caespitosa",
		"Calandrinia compacta",
		"Calceolaria arachnoidea",
		"Calceolaria biflora",
		"Calceolaria filicaulis",
		"Calceolaria glandulosa",
		"Calopappus acerosus",
		"Cardionema ramosissima",
		"Carex macloviana",
		"Carex pleioneura",
		"Carex setifolia",
		"Cerastium arvense",
		"Cheilanthes glauca",
		"Cheilanthes hypoleuca",
		"Cheilanthes mollis",
		"Cistanthe grandiflora",
		"Cistanthe picta",
		"Conanthera campanulata",
		"Convolvulus chilensis",
		"Conyza andina",
		"Corrigiola squamosa",
		"Cortaderia speciosa",
		"Cynodon dactylon",
		"Deyeuxia velutina",
		"Dioscorea humifusa",
		"Diplolepis mucronata",
		"Draba pusilla",
		"Dysphania ambrosioides",
		"Eleocharis bonariensis",
		"Equisetum bogotense",
		"Erigeron andicola",
		"Erythranthe lutea",
		"Euphorbia portulacoides",
		"Festuca acanthophylla",
		"Festuca rigescens",
		"Galium trichocarpum",
		"Gamochaeta chamissonis",
		"Gamochaeta stachydifolia",
		"Gavilea longibracteata",
		"Geranium berteroanum",
		"Geranium core-core",
		"Glandularia berteroi",
		"Glandularia laciniata",
		"Glandularia sulphurea",
		"Hydrocotyle bonariensis",
		"Hydrocotyle ranunculoides",
		"Hypochaeris thrincioides",
		"Jarava plumosa",
		"Jarava pogonathera",
		"Juncus balticus",
		"Leucheria rosea",
		"Leucocoryne ixioides",
		"Marrubium vulgare",
		"Melica argentata",
		"Melica poecilantha",
		"Menonvillea flexuosa",
		"Mentha aquatica",
		"Mentha suaveolens",
		"Mentha x",
		"Miersia chilensis",
		"Mirabilis ovata",
		"Montiopsis andicola",
		"Montiopsis sericea",
		"Myostemma advena",
		"Nassauvia cumingii",
		"Nassauvia looseri",
		"Nassella chilensis",
		"Nastanthus caespitosus",
		"Nasturtium officinale",
		"Nicotiana acuminata",
		"Olsynium junceum",
		"Oxalis erythrorhiza",
		"Oxalis megalorrhiza",
		"Oziroë biflora",
		"Pappostipa chrysophylla",
		"Pappostipa frigida",
		"Pasithea caerulea",
		"Paspalum dilatatum",
		"Pellaea myrtillifolia",
		"Perezia carthamoides",
		"Phacelia pinnatifida",
		"Phacelia secunda",
		"Phycella cyrtanthoides",
		"Piptochaetium panicoides",
		"Pleurosorus papaverifolius",
		"Poa holciformis",
		"Poa pratensis",
		"Polygala gnidioides",
		"Pseudognaphalium cabrerae",
		"Pseudognaphalium gayanum",
		"Pseudognaphalium viravira",
		"Quinchamalium chilense",
		"Reyesia chilensis",
		"Rorippa sylvestris",
		"Rytidosperma pictum",
		"Sanicula crassicaulis",
		"Senecio adenotrichius",
		"Sisyrinchium cuspidatum",
		"Sisyrinchium graminifolium",
		"Sisyrinchium striatum",
		"Solenomelus pedunculatus",
		"Spergula pissisi",
		"Stachys grandidentata",
		"Trichopetalum plumosum",
		"Triptilion spinosum",
		"Trisetum caudulatum",
		"Tropaeolum tricolor",
		"Tweedia birostrata",
		"Urtica berteroana",
		"Urtica gracilis",
		"Valeriana bridgesii",
		"Valeriana vaga",
		"Viola montagnei",
		"Weberbauera imbricatifolia",
	],
}

export const coverageOptions = ["1:<5%", "2:5-10%", "3:10-25%", "4:25-50%", "5:50-75%", "6:75-100%"]

export const exposureOptions = [
	"	Plano",
	"Norte",
	"Noreste",
	"Este",
	"Sureste",
	"Sur",
	"Suroeste",
	"Oeste",
	"Noroeste",
	"Cot distancia",
]

export const drainageOptions = ["Impedido", "Normal", "Excesivo", "Cot distancia"]

export const topographyOptions = [
	"Plano",
	"Cumbre",
	"Media ladera",
	"Baja ladera",
	"Fondo quebrada",
	"Terraza",
	"Cot a distancia",
]

export const substrateOptions = ["Rocoso", "Arenoso", "Terroso", "Orgánico", "Cot a distancia"]

export const slopeOptions = ["0 a 10%", "10 a 30%", "30 a 60%", "mayor que 60%", "cot distancia"]

export const interventionOptions = [
	"Quema",
	"Quema floreo",
	"Floreo ganado",
	"Ganado",
	"Corta con manejo",
	"No aparente",
	"Cot a distancia",
]

export const formationOptions = [
	"Bosque",
	"Bosque con suculentas",
	"Matorral con suculentas",
	"Formación de suculentas",
	"Matorral",
	"Pradera",
	"Pradera con árboles",
	"Pradera con arbustos",
	"Zona de vegetación escasa",
	"Otras superficies",
	"Turbera esfangosa",
	"Turbera pulvinada",
]

export const coverageGroundOptions = ["Densa", "Semidensa", "Abierta", "Muy abierta", "Rala", "ZVE"]

export const percentageBySpeciesOptions = [
	"10",
	"20",
	"30",
	"40",
	"50",
	"60",
	"70",
	"80",
	"90",
	"100",
]

export const developmentOptions = [
	"Regeneración (>0,5 m)",
	"Brinzal (0,5-2 m)",
	"Monte bravo (2-8m)",
	"Latizal (8-20m <20dap)",
	"Fustal (dap 20-55cm)",
	"Maduro (dap >55 sin pudri)",
	"Sobremaduro (>55 dap, con pudric)",
]

export const originOptions = [
	"Monte alto (de semillas)",
	"Monte medio (semilleros y reb tocon)",
	"Monte bajo (rebr de tocón o raiz)",
]

export const healthStatusOptions = ["Bueno", "Regular", "Malo"]

export const contentSurveyOptions = [
	{
		id: "cobertura",
		label: "Cobertura",
		options: coverageOptions,
		placeholder: "Selecciona una cobertura",
	},
	{
		id: "exposicion",
		label: "Exposición",
		options: exposureOptions,
		placeholder: "Selecciona una exposición",
	},
	{
		id: "drenaje",
		label: "Drenaje",
		options: drainageOptions,
		placeholder: "Selecciona un drenaje",
	},
	{
		id: "topografia",
		label: "Topografía",
		options: topographyOptions,
		placeholder: "Selecciona una topografía",
	},
	{
		id: "sustrato",
		label: "Sustrato",
		options: substrateOptions,
		placeholder: "Selecciona un sustrato",
	},
	{
		id: "pendiente",
		label: "Pendiente",
		options: slopeOptions,
		placeholder: "Selecciona una pendiente",
	},
	{
		id: "intervencion",
		label: "Intervención",
		options: interventionOptions,
		placeholder: "Selecciona una intervención",
	},
	{
		id: "formacion",
		label: "Formación",
		options: formationOptions,
		placeholder: "Selecciona una formación",
	},
	{
		id: "coberturaTerrero",
		label: "Cobertura Terrero",
		options: coverageGroundOptions,
		placeholder: "Selecciona una cobertura de terreno",
	},
	{
		id: "porcentajePorEspecie",
		label: "Porcentaje por Especie",
		options: percentageBySpeciesOptions,
		placeholder: "Selecciona un porcentaje por especie",
	},
	{
		id: "desarrollo",
		label: "Desarrollo",
		options: developmentOptions,
		placeholder: "Selecciona un desarrollo",
	},
	{
		id: "origen",
		label: "Origen",
		options: originOptions,
		placeholder: "Selecciona un origen",
	},
	{
		id: "estadoSanitario",
		label: "Estado Sanitario",
		options: healthStatusOptions,
		placeholder: "Selecciona un estado sanitario",
	},
]
