export const laSpecies = [
	"Acacia caven",
	"Aristotelia chilensis",
	"Cryptocarya alba",
	"Drimys winteri",
	"Jubaea chilensis",
	"Kageneckia angustifolia",
	"Kageneckia oblonga",
	"Lithraea caustica",
	"Luma chequen",
	"Malus domestica (Borkh.)",
	"Maytenus boaria",
	"Porlieria chilensis",
	"Prosopis chilensis",
	"Pyrus cummunis",
	"Quillaja saponaria",
	"Salix humboldtiana",
	"Schinus latifolius",
	"Schinus polygamus",
]
